name: Testkit
on:
  push:
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/testkit.yml"
      - "composer.json"
  pull_request:
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/testkit.yml"
      - "composer.json"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '7.1', '8.1', '8.4' ]
    name: PHP ${{ matrix.php-versions }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpcs, composer

      - name: Get php version
        run: 'php -v'

      - name: Setup Composer dependencies
        run: 'composer update'

      - name: Run PHPUnit Tests
        run: 'php ./vendor/bin/phpunit ./tests/'

      - name: Run PHPCS
        run: 'phpcs'
